discord_bog:
  discord_token_key: BOG_BOT_TOKEN
  bsc_rpc_url: https://bsc-dataseed.binance.org/
  token_name: BOG
  token_addr: "0xB09FE1613fE03E7361319d2a43eDc17422f36B09"
  avatar_file: bog.png

discord_eth:
  discord_token_key: ETH_BOT_TOKEN
  bsc_rpc_url: https://bsc-dataseed.binance.org/
  token_name: ETH
  token_addr: "0x2170Ed0880ac9A755fd29B2688956BD959F933F8"
  avatar_file: eth.png

discord_cake:
  discord_token_key: CAKE_BOT_TOKEN
  bsc_rpc_url: https://bsc-dataseed.binance.org/
  token_name: CAKE
  token_addr: "0x0E09FaBB73Bd3Ade0a17ECC321fD13a19e81cE82"
  avatar_file: cake.png

discord_bnb:
  discord_token_key: BNB_BOT_TOKEN
  bsc_rpc_url: https://bsc-dataseed.binance.org/
  token_name: BNB
  token_addr: "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c"
  avatar_file: bnb.png
  